# Generated by Django 2.2.2 on 2021-04-15 09:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app01', '0002_auto_20210412_2031'),
    ]

    operations = [
        migrations.CreateModel(
            name='Email',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('send_user', models.CharField(max_length=10)),
                ('recv_user', models.CharField(max_length=10)),
                ('title', models.TextField()),
                ('content', models.TextField()),
            ],
        ),
    ]
