# Generated by Django 2.2.2 on 2021-04-15 09:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app01', '0003_email'),
    ]

    operations = [
        migrations.AlterField(
            model_name='email',
            name='recv_user',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='email',
            name='send_user',
            field=models.CharField(max_length=100),
        ),
    ]
